sudo: required
language: bash
services:
  - docker

before_script:
  - docker build . --tag=$APP_IMAGE
script:
  - docker run --rm -e KBC_DEVELOPERPORTAL_APP -e KBC_DEVELOPERPORTAL_VENDOR -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e APP_IMAGE -e XERO_CREDENTIALS_TYPE -e XERO_CONSUMER_KEY -e XERO_CONSUMER_SECRET -e XERO_PRIVATE_RSA_KEY -e XERO_PUBLIC_CONSUMER_KEY -e XERO_PUBLIC_CONSUMER_SECRET --entrypoint 'python3' $APP_IMAGE -m pytest
after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true

  script: ./deploy.sh
  on:
    tags: true

